sudo: required
dist: precise
language: scala
scala:
  - 2.11.11
jdk:
  - oraclejdk8
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.custom-cache
script:
  - sbt -jvm-opts .jvmopts-travis clean coverage ++$TRAVIS_SCALA_VERSION fixCheck test coverageReport coverageAggregate
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - >
    test "${TRAVIS_PULL_REQUEST}" = 'false' &&
    test "${TRAVIS_REPO_SLUG}" = 'maocorte/NSDb' &&
    test "${TRAVIS_JDK_VERSION}" = 'oraclejdk8' &&
    sh "$TRAVIS_BUILD_DIR/travis-credentials.sh" &&
    sbt +publish
